### ISSUE TITLE
useless files are added on 12 dev branch

### ISSUE THREAD

**Issue by unicornx** [riscv-android-src/platform-prebuilts-ndk#1]
I find there are extra files should not be involved in 
```
commit 4bb9dfe16facfdb96c0793c41030eb8e107ff473 (HEAD -> riscv64-android-12.0.0_dev, origin/riscv64-android-12.0.0_dev)
Author: CHEN GUOYIN <chenguoyin.cgy@alibaba-inc.com>
Date:   Mon Jan 17 17:00:08 2022 +0800

    add riscv64 ndk
    
    Signed-off-by: CHEN GUOYIN <chenguoyin.cgy@alibaba-inc.com>
    Change-Id: I84c4590a99787a5131b13e736aef6e1250acd041

```

For example:
```
$ pwd
/aosp/wangchen/dev-ndk/platform-prebuilts-ndk/current/sources/cxx-stl/llvm-libc++/libs/arm64-v8a
$ ls
libc++.a.21  libc++.a.23  libc++.a.25  libc++.a.27  libc++.a.29  libc++_shared.so  libc++.so.22  libc++.so.24  libc++.so.26  libc++.so.28  libc++_static.a
libc++.a.22  libc++.a.24  libc++.a.26  libc++.a.28  libc++abi.a  libc++.so.21      libc++.so.23  libc++.so.25  libc++.so.27  libc++.so.29  libunwind.a
```

In init baseline: commit 577cdf79feb1a24c6b4da9fa2bdadfb33d218129, there are only 4 files under the same folder:
```
$ pwd
/aosp/wangchen/dev-ndk/platform-prebuilts-ndk/current/sources/cxx-stl/llvm-libc++/libs/arm64-v8a
$ ls
libc++abi.a  libc++_shared.so  libc++_static.a  libunwind.a
```

There are similar cases in several locations for this repo, I believe in commit 4bb9dfe16facfdb96c0793c41030eb8e107ff473, too many useless files are added by mistake.

**Comment by guoyinchen** [comment]
those files is copied by ndk build folder copy, so bring some extra files. Please remove those unused one. Thanks.

**Comment by unicornx** [comment]
After some investigation, I find the files may be copied from the "current/sources" under branch `riscv64-android-10.0.0_dev`, because when I diff the "current/sources" between `riscv64-android-10.0.0_dev` and `riscv64-android-12.0.0_dev`, files are all the same except some files new introduced for aosp 12.

I think such update is not correct, we should make changes based on aosp 12, but not involves files belongs to 10.
It's tricky that current aosp 12 build and run w/o problem, still need deep investigation.

**Comment by unicornx** [comment]
closed with https://github.com/riscv-android-src/platform-prebuilts-ndk/pull/2
